spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.201.64.102:3306/commentset
#    url: jdbc:mysql://localhost:3306/commentset
    username: root
    password: 333
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  web:
    resources:
      static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources
  mvc:
    view:
      prefix: classpath:/templates/
logging:
  level:
    com.jancoyan.commentset.mapper: debug
server:
  port: 9090
